FROM node:22-bullseye

WORKDIR /app

# Instalar Vue CLI globalmente
RUN npm install -g @vue/cli

# Exponer puertos para las aplicaciones Vue
EXPOSE 8080 3000 5173

# Mantener el contenedor corriendo
CMD ["/bin/bash"]